language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sharktamer
  password:
    secure: cUPYoC901jIjK5orirQpIz2+NdoKyB9AeMP04uDqfgreXBibk8dKNXd/aBsOC7t3bxyu2KD1rnY3o4A1R8TulBGEHekI+Jgn5wL68z7oboX/3FsjrsJg4PR5ElInog42EN9Cmf8GPFUAOKrwAMMjv+Q1DsRVe0jRgG+hz7Nt8Na5YidEO++fNnIZHgsJrsyCeYP2tM4+2vmgIOp4qW+OjVA//EgRuOC3thgBaVqiJY78cKwttRaVPHJ0E2xni6LNRF+6s8jvypxWuhPP6gUCsK1GjRzGdhbhkIY2tJm2TTpK2IEJKdXjj/4KQzU4dbZapYZiW7Ki+zDlcY6MJQ8oQ109H/daqfkCwU36aYfdVrdCWXQ9h77wrrVedazt6zGa4/OMwLfSq9lcr/b8b2CoXKTKtwZZXYSj10PXMUgHAgne1d4VFWayHRDxYMSwOdRT/beukxrCuw2+rzBz6yfKzqx9egi1Z71T+Riqk9Pkiimu0ugBhwL3OjyfFcAo8l2iSYM/yRel2LJH1iw4YuR+pjrNtyJAKe0dbdfnlVR5KMuJIXWjyzCPbELYrb7UG3nf0bX3gkh7K2OaF0x992xbTGZzeQylcTNO93gC9LkIOlgeEV0mVH/T09K5hjQ26CdLsU5cS8DqBD0FDjyu9s4itiY0HJsQcnBOAVnDRKujsx4=
  on:
    tags: true
    repo: shanedonohoe/poku
    python: 3.6
