language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sharktamer
  password:
    secure: bY/XY4E4E1kFmczGsVY9EJU8FYrLqgVR1d8PePpVrjxCnQqY5CJYPtT1vQVP++jQFMK0IpPyfs5kK8qCjuQU4wVd2unmZsP6TPDy5507+8QhMlYM5jglrLZ8rNhFgtYYjyYIVUh5lef/JfzpIgV4NzwaPYZgwLfH5RQYXbgYcGNvKNzRzgmFlHwrOhFt+yIc5VUQ/iWkv4CwSR0u6fh3ZEag7w0eW+L1OinZhb4K+CsHh088fyO12tYso7cT4u6pgEd2XMWRNVtGov74etuZ/e46bE1WX8mMHjhcwdV+rgU/4jTXjrqXMlG6dB1/FX2M48LySqnhk20iigVzoVTjpIQVMJR8oOsgSuKd30vIjd8aIC4ju+omrcHTiOZlFidtuK32qxSh49SGmWrSQWMgyJlmkFthz1ZAeQr5qxxHfWJED4ASywlY4DgFIiO+8OSxf7kyuncZ1a8lRmyJUAaysASLGgFojzSGojI+pRISmJWY6tHfdCqebvX0n8FAb/rZieoytfEefeUCT84khKdvzS1gPIXDTy3QjnRPGeCdRMXr805NuuTeNbGnXmjjlx20w37P4Ubt1dZljE5QdJFCNL2T8l8/uVqSC74/a0xgQqmD0SFsRLzOp2lEX4udeXcF8IQsPmSywi/a8IxcrR92bPuTQE9hsCPOsD5aE3AinNg=
  on:
    tags: true
    repo: shanedonohoe/poku
    python: 3.6
